"""users table

Revision ID: 2f964df6b9f2
Revises: 
Create Date: 2025-07-11 02:28:27.884849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f964df6b9f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('abstracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abstracts_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_abstracts_date_submitted'), ['date_submitted'], unique=False)
        batch_op.create_index(batch_op.f('ix_abstracts_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_abstracts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abstracts_institution'), ['institution'], unique=False)
        batch_op.create_index(batch_op.f('ix_abstracts_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abstracts_year'))
        batch_op.drop_index(batch_op.f('ix_abstracts_institution'))
        batch_op.drop_index(batch_op.f('ix_abstracts_id'))
        batch_op.drop_index(batch_op.f('ix_abstracts_field'))
        batch_op.drop_index(batch_op.f('ix_abstracts_date_submitted'))
        batch_op.drop_index(batch_op.f('ix_abstracts_country'))

    op.drop_table('abstracts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
