"""Add file upload support

Revision ID: 45d0145f0b58
Revises: fbde80a7c5c7
Create Date: 2025-11-21 12:23:43.266892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d0145f0b58'
down_revision = 'fbde80a7c5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=10), nullable=False))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abstracts', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
