"""new fields in users table

Revision ID: a11af13a48cd
Revises: 03a89f23d4b3
Create Date: 2025-07-11 09:36:34.326511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11af13a48cd'
down_revision = '03a89f23d4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_date')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
